Energinet-DataHub/geh-timeseries

NOTICE.md
Update NOTICE.md to use coverlet 3.0.3
=> Update NOTICE.md to use coverlet 3.0.3

.licenserc.json
=> include terraform in license check

source/GreenEnergyHub.TimeSeries/GreenEnergyHub.TimeSeries.sln, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Application/GreenEnergyHub.TimeSeries.Application.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/DateTime/IZonedDateTimeService.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/DateTime/ResolutionStrategy.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/DateTime/ZonedDateTimeService.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/GreenEnergyHub.TimeSeries.Core.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/Interval.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Core/Json/JsonSerializer.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/GreenEnergyHub.TimeSeries.Domain.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/GreenEnergyHub.TimeSeries.Infrastructure.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.TestCore/AutoMoqDataAttribute.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.TestCore/GreenEnergyHub.TimeSeries.TestCore.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.TestCore/InlineAutoMoqDataAttribute.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/GreenEnergyHub.TimeSeries.Tests.csproj
The purpose of this PR is to add the timeseries solution and our basic projects.
Our first actual host and pipelines will be coming later.
This PR adds:
* Solution file
* Domain project
* Application project
* Infrastructure project
* Core project (with code we had in charges)
* TestCore project (with code we had in charges)
* Test project
* #37
=> Add timeseries solution and basic projects

.github/actions/azure-core-tools-install/action.yml, .github/workflows/message-receiver-cd.yml, .github/workflows/message-receiver-ci.yml, source/GreenEnergyHub.TimeSeries/deploy-functions.cmd
The purpose of this PR is to add the GitHub workflows for CI and CD of the message receiver.
* A CI pipeline is added to unit test the message receiver code as part of the PR gate
* A CD pipeline is added to deploy the Azure Function into the infrastructure
* A GitHub action for installing Azure Core Tools is added (in preparation for .NET 5)
* The script for helping developers deploy the Azure Function to their Sandbox is added
NOTE: This PR should not be merged until #79 has reached main.
* #37 
* #79
=> Add pipeline workflows for message receiver

.github/workflows/sonarcloud-dotnet.yml, .github/workflows/sonarcloud.yml
The purpose of this PR is to add a workflow that checks the timeseries domains .NET code for vulnerabilities using SonarCloud
For now, it will only be a guideline, no restrictions will be enabled as part of the PR gateway at this point.
* Adds workflow for checking code though SonarCloud
=> Add SonarCloud workflow for checking the .NET code of the time series domain

source/GreenEnergyHub.TimeSeries/GreenEnergyHub.TimeSeries.sln, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Application/GreenEnergyHub.TimeSeries.Application.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Application/IMessageDispatcher.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/GreenEnergyHub.TimeSeries.Domain.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/Notification/Series.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/Notification/TimeSeriesResolution.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/GreenEnergyHub.TimeSeries.Infrastructure.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Channel.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/IServiceBusSender.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/MessageDispatcher.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/MessageExtractor.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Registration/MessagingRegistrator.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Registration/RegistrationExtensions.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/DefaultJsonMapperFactory.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/IJsonOutboundMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/IJsonOutboundMapperFactory.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/JsonMessageDeserializer.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/JsonMessageSerializer.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MessageDeserializer.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/NoMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/ServiceBusChannel.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/ServiceBusSender.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/Startup.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/TimeSeriesHttpTrigger.cs
This PR mostly copies code from Charges domain. No new functionality added besides dependency injection.
The PR adds the messaging framework to time series domain, and uses it in MessageReceiver
* #72
=> Add messaging framework and use it in messagereceiver

.github/workflows/infrastructure-cd.yml
We forgot to add two variables to the infrastructure-cd pipeline. This Pr will add them.
=> added spn_object_id and tenant_id to varibles on infra-cd

.github/workflows/message-receiver-cd.yml
The purpose of this PR is to fix the message receiver CD workflow which seems to be broken.
* #77
=> Fix whitespace issue with dotnet version in MessageReceiver CD workflow

.github/workflows/streaming-job.yml
The purpose of this PR is the fix the streaming job workflow which is currently broken.
=> Fix issue with wheel in streaming job pipeline

.github/workflows/sonarcloud-python.yml
The purpose of this PR is to add a pipeline that uses SonarCloud to analyze our Python code
=> Add SonarCloud pipeline analyzing Python

build/infrastructure/README.md
With this PR we add further instructions to infrastructure readme regarding terraform and Azure.
=> Update readme with instructions to set Azure subscription

README.md
This PR updates the Time Series road map with current program increment goals. 
None
=> Update Time Series Road Map with current program increment goals

source/streaming/tests/conftest.py
E128 continuation line under-indented for visual indent
=> Fix E128 continuation line under-indented

source/streaming/geh_stream/schemas/schema_factory.py
=> E128 continuation line under-indented

source/streaming/tests/streaming_utils/conftest.py
=> Fix W291 trailing whitespace

.github/workflows/streaming-job.yml
This PR will change the trigger on the Streaming-Job to now trigger on changes made either to the workflow or the patch source/streaming/** where the jobs code is located.
=> Update Streaming-job.yml trigger

.github/workflows/codecov-ci.yml, codecov.yml
The purpose of this PR is to add code coverage analysis to the time series domain.
This PR:
* Adds settings for code coverage
* Adds pipeline for analysing the coverage
=> Introduce code coverage to the time series domain

.github/utilities/md-spellcheck/wordlist.txt, docs/contracts.md
This PR documents the **time series** integration event targeting the needs of the Aggregations Domain.
Note: Creating the IntegrationEventContract.proto file and publishing of this type of time series event will follow in a subsequent story.
* #90
=> Document integration event for TimeSeries

.github/dependabot.yml
=> build: fix dependabot directory

.github/actions/setup-terraform-options/action.yml
This PR fixes an error in the Terraform action for setting up terraform options.
=> fix: Error in setup terraform action

README.md
Added the code coverage badge to the README of the time series repo. 
* none
=> docs: Add CodeCoverage badge to README

.github/actions/dotnet-build-and-test/action.yml, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/Application/Handlers/TimeSeriesCommandHandlerTests.cs
Wrong Attribute in build-and-test action. Unittests were not run in CI steps.
=> build - category attribute changed to UnitTest

source/streaming/geh_stream/schemas/schema_factory.py
This PR will fix indentation in parsed_protobuf_schema as an addendum to #111
=> Fix indentation in parsed_protobuf_schema

source/streaming/geh_stream/streaming_utils/__init__.py
New __init__.py in streaming_utils should cause streaming_utils to be re-introduced in wheel-fil
=> Re-introduce streaming_utils in wheel

source/streaming/geh_stream/streaming_utils/input_source_readers/__init__.py
Import ProtobufMessageParser to allow it to be used within wheel
=> Import ProtobufMessageParser

README.md
This PR updates the PI objectives in the Domain Road Map section to match those of PI6.
Also, it was decided to remove the objectives of the recent PI's as it was not found relevant to keep.
* #0000
=> docs: Added PI6 objective

README.md
Code coverage has temporarily been deactivated due some strange results. While this is being investigated and fixed, the code cov badge on the repo front page (README) is out commented.
* #0000
=> docs: Temporarily remove code-cov badge in repo README

.github/CODEOWNERS
Update codeowners to correct list
* #0000
=> Update time series codeowners

.github/CODEOWNERS
=> Add team Joules as code owners

.github/workflows/sonarcloud-dotnet.yml, .gitignore, .licenserc.json, source/TimeSeries/MessageReceiver.IntegrationTests/Assets/TestDocuments.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Assets/Valid_Hourly_CIM_TimeSeries.xml, source/TimeSeries/MessageReceiver.IntegrationTests/Fixtures/TimeSeriesFunctionAppCollectionFixture.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Fixtures/TimeSeriesFunctionAppFixture.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Functions/TimeSeriesTriggerTests.cs, source/TimeSeries/MessageReceiver.IntegrationTests/MessageReceiver.IntegrationTests.csproj, source/TimeSeries/MessageReceiver.IntegrationTests/functionapphost.settings.json, source/TimeSeries/MessageReceiver.IntegrationTests/integrationtest.local.settings.json.sample, source/TimeSeries/MessageReceiver/MessageReceiver.csproj, source/TimeSeries/MessageReceiver/Program.cs, source/TimeSeries/MessageReceiver/SimpleInjector/SimpleInjectorActivator.cs, source/TimeSeries/MessageReceiver/SimpleInjector/SimpleInjectorScopedRequest.cs, source/TimeSeries/MessageReceiver/SimpleInjector/SimpleInjectorServiceProviderAdapter.cs, source/TimeSeries/MessageReceiver/Startup.cs, source/TimeSeries/MessageReceiver/TimeSeriesFunctionNames.cs, source/TimeSeries/MessageReceiver/TimeSeriesIngestion.cs, source/TimeSeries/MessageReceiver/host.json, source/TimeSeries/MessageReceiver/local.settings.sample.json, source/TimeSeries/TimeSeries.sln
…time series
Added a new solution containing only a HttpTrigger function for submitting time series.
* #326
=> Added new TimeSeries solution containing only Ingestion function for time series submit

.github/actions/publish-release-contents/action.yml
=> change name of step

.github/workflows/cd.yml, .github/workflows/ci.yml, build/primary/main/func-message-receiver.tf, build/primary/main/kv-shared-resources.tf, source/TimeSeries/MessageReceiver.IntegrationTests/Fixtures/AuthorizationConfiguration.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Fixtures/ClientCredentialsSettings.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Fixtures/TimeSeriesFunctionAppFixture.cs, source/TimeSeries/MessageReceiver.IntegrationTests/Functions/TimeSeriesTriggerTests.cs, source/TimeSeries/MessageReceiver.IntegrationTests/MessageReceiver.IntegrationTests.csproj, source/TimeSeries/MessageReceiver.IntegrationTests/integrationtest.local.settings.json.sample, source/TimeSeries/MessageReceiver/MessageReceiver.csproj, source/TimeSeries/MessageReceiver/Program.cs, source/TimeSeries/MessageReceiver/local.settings.sample.json
Add missing JWT token specific variables for terraform and function settings.
* #325
=> add jwt token specific settings variables

build/primary/main/kv-shared-resources.tf
Remove unused keyvault secrets for swl.
* #328
=> remove unused keyvault secrets

build/primary/main/evh-timeseries.tf, build/primary/main/func-message-receiver.tf
Add terraform to create internal event hub for received timeseries.
* [586](https://app.zenhub.com/workspaces/joules-5fd22a1a59e4740018f5ab5a/issues/energinet-datahub/geh-aggregations/586)
=> Add internal timeseries eventhub

.github/workflows/ci.yml
This Pr will update the workflow versions to 5.0.0 along with the .Net version upgraded to 5.0.404
* #375
=> build: updated ci workflows to version 5.0.0

source/TimeSeries/Infrastructure/EventHub/EventHubSender.cs, source/TimeSeries/Infrastructure/Registration/EnvironmentHelper.cs, source/TimeSeries/TimeSeriesBundleIngestor/Program.cs
This PR will add an `EnvironmentHelper` to help with getting environment variables.
* #374
=> refac: Add EnvironmentHelper

source/TimeSeries/Application/Dtos/MarketParticipantDto.cs, source/TimeSeries/TimeSeries.sln.DotSettings
Had some changes which were not in my last commit.
* #374
=> refac: added missing warning fixes

.github/workflows/ci.yml, build/primary/main/func-time-series-bundle-ingestor.tf
This PR will update the name of the az-function resource to reestablish the cd pipeline.
* #374
=> bug: update az-function name to time-series-bundle-ingestor

source/TimeSeries/Application/TimeSeriesForwarder.cs, source/TimeSeries/Infrastructure/Infrastructure.csproj, source/TimeSeries/Infrastructure/Serialization/IJsonSerializer.cs, source/TimeSeries/Infrastructure/Serialization/JsonSerializer.cs, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs, source/TimeSeries/TimeSeriesBundleIngestor/Startup.cs, source/TimeSeries/UnitTests/Infrastructure/JsonSerializerTests.cs
Add custom `JsonSerializer` to be able to serialize and deserialize `Instant`
* #376
=> add json serializer

build/databricks_streaming_cluster/main/providers.tf, build/primary/main/providers.tf
=> Fix for issue with databricks pipeline

source/databricks/package/__init__.py, source/databricks/package/table_creator.py, source/databricks/package/timeseries_publisher.py
Create delta table for processed timeseries if it doesn't exist.
* #376
=> create delta table if not exists

source/databricks/streaming-jobs/timeseries_persister_streaming.py
=> fix pipeline

.github/workflows/ci.yml
=> Add workflow_dispatch

.github/ISSUE_TEMPLATE/issue.md
Moved from 442 because of protected branch
* #442
=> issue template

source/TimeSeries/Infrastructure/EventHub/EventDataFactory.cs, source/TimeSeries/Infrastructure/EventHub/EventHubSender.cs, source/TimeSeries/Infrastructure/EventHub/IEventDataFactory.cs, source/TimeSeries/TimeSeriesBundleIngestor/Program.cs, source/TimeSeries/UnitTests/Infrastructure/EventHub/EventDataFactoryTests.cs, source/TimeSeries/UnitTests/Infrastructure/TimeSeriesBundleDtoValidatingDeserializerTests.cs, source/TimeSeries/UnitTests/UnitTests.csproj
Description
------------
This PR will ensure that when sending an event to the EventHub, CorrelationId is set upon the message.
Reference
----------
#426
=> feat: CorrelatioId set on Events to EventHub

source/TimeSeries/TimeSeriesBundleIngestor/Startup.cs, source/TimeSeries/TimeSeriesBundleIngestor/TimeSeriesBundleIngestor.csproj
This PR will change our End-To-End Transaction telemetry overwatch from this:![image](https://user-images.githubusercontent.com/6780460/161263053-4323cf6d-508c-4349-b764-d9ab9fd57a1c.png)
To this
=> Add FunctionTelemetryScopeMiddleware

source/TimeSeries/TimeSeriesBundleIngestor/TimeSeriesBundleIngestor.csproj
request response logging upgrade 1.2.1
* #0000
=> logging upgrade 1.2.1

build/primary/main/func-time-series-bundle-ingestor.tf, build/primary/main/kv-shared-access-policies.tf, build/primary/main/kv-shared-resources.tf
=> add keyvault references

build/databricks_streaming_cluster/main/main.tf
=> 463 fix args

.github/actions/dotnet-prepare-outputs/action.yml, .github/actions/publish-release-contents/action.yml, .github/workflows/ci.yml
Use previously constructed artifacts in CI pipeline.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/329
=> Update CI build

source/databricks/package/timeseries_publisher.py
=> fix write mode

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/ci.yml, README.md, source/databricks/README.md, source/databricks/package/codelists/colname.py, source/databricks/package/codelists/resolution.py, source/databricks/package/data_loader.py, source/databricks/package/schemas/eventhub_timeseries_schema.py, source/databricks/package/schemas/time_series_points_schema.py, source/databricks/package/schemas/time_series_raw_schema.py, source/databricks/package/schemas/time_series_unprocessed_schema.py, source/databricks/package/table_creator.py, source/databricks/package/timeseries_persister.py, source/databricks/package/timeseries_persister_streaming.py, source/databricks/package/timeseries_publisher.py, source/databricks/package/timeseries_publisher_streaming.py, source/databricks/package/transforms/jsonTransformer.py, source/databricks/setup.py, source/databricks/tests/conftest.py, source/databricks/tests/integration/conftest.py, source/databricks/tests/integration/time_series_persister/conftest.py, source/databricks/tests/integration/time_series_persister/test_time_series_persister.py, source/databricks/tests/integration/time_series_publisher/test_time_series_publisher.py, source/databricks/tests/integration/utils.py, tox.ini, wordlist.txt
This PR adds DX improvements.
- Makes [Black](https://github.com/psf/black#readme) the default formatting provider.
- Formats the file on save.
- Removes Autopep8 from the docker file, because of the switch to Black.
- Sets python default interpreter path to the one in the docker container
- Sets language server to Jedi
- Adds styles and formatting section to databricks readme
The files that are changed are Dockerfile, devcontainer.json, tox.ini and the ReadMe files
the rest of the changes are more or less formatting done by running Black on the repo
* #0000
=> Make DX with python in vscode better

source/databricks/README.md, wordlist.txt
Align with changes in [Wholesale PR 158](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/158)
* #0000
=> Add links to tox.ini and ci.yml

.github/workflows/cd.yml, .github/workflows/ci.yml
* https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/421
=> Update CI and CD

build/infrastructure/main/dbwj-persister.tf, build/infrastructure/main/dbwj-publisher.tf
Python wheel from geh-timeseries and opengeh-wholesale shared name and location in Databricks file system effectively causing overwrite on each pull-request.
* https://github.com/Energinet-DataHub/opengeh-wholesale/issues/32
=> Fix python wheel collision

source/databricks/package/timeseries_persister.py, source/databricks/package/transforms/jsonTransformer.py
This Pr will add the `storedTime` column to the published timeseries.
=> feat: Add stored time

build/infrastructure/main/dbwj-publisher.tf
=> Make persister retry infinite

source/TimeSeries/Application/TimeSeriesForwarder.cs, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs
* https://github.com/Energinet-DataHub/opengeh-wholesale/issues/32
=> fix: Prevent json file names breaking streaming

build/infrastructure/main/dbwj-persister.tf, build/infrastructure/main/dbwj-publisher.tf
```max_retries``` does not apply to the runs when not placed inside the ```tasks``` section. I cannot find documentation mentioning this, but it appears to work now.
```max_concurrent_runs``` and ```always_running``` are not affected.
=> bug: max_retries not applying.

.devcontainer/devcontainer.json
=> refac: only format on save on python files

.gitattributes
This PR should avoid the problem where lots of files shows up as changes in Git when working in mixed environment (.NET on Windows and pyspark on Linux in Docker).
In order to update current working files make sure you don't have any pending changes and execute the following commands:
```
git rm --cached -r .
git reset --hard
```
=> feat: Use Windows line endings

.github/dependabot.yml
Dependabot had stopped working because the .NET solution file folder had changed without updating dependabot.yml.
* #0000
=> fix: Fix dependabot.yml

source/TimeSeries/Application/Application.csproj, source/TimeSeries/Infrastructure/Infrastructure.csproj, source/TimeSeries/IntegrationTests/IntegrationTests.csproj, source/TimeSeries/TestCore/TestCore.csproj, source/TimeSeries/TimeSeriesBundleIngestor/Program.cs, source/TimeSeries/TimeSeriesBundleIngestor/TimeSeriesBundleIngestor.csproj, source/TimeSeries/UnitTests/UnitTests.csproj
* Updated / consolidated all dependency NuGet packages
* Changed registration of Application Insights to use new extension
=> Use Application Insights extension

.github/workflows/cd.yml, .github/workflows/ci.yml
Use v8 version for reusable workflows/actions
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/479
=> Use v8 version for reusable workflows/actions

source/TimeSeries/Application/Application.csproj, source/TimeSeries/Infrastructure/Infrastructure.csproj, source/TimeSeries/IntegrationTests/IntegrationTests.csproj, source/TimeSeries/TimeSeriesBundleIngestor/TimeSeriesBundleIngestor.csproj, source/TimeSeries/UnitTests/TimeSeriesBundleToJsonConverterTests.cs
=> update nuget packages

obsolete/source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/local.settings.sample.json
Reference: https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/9
=> Remove AzureWebJobsDashboard setting

source/contracts/enums/timeseries-quality.json, source/databricks/package/codelists/__init__.py, source/databricks/package/codelists/timeseries_quality.py
Ads contract test of timeseries quality enum
* #186
=> added test of timeseries quality match contract

build/infrastructure/main/dbwj-alert-persister.tf, build/infrastructure/main/dbwj-alert-publisher.tf
=> build: Implemeted alerts for publisher and persister streaming job

.github/workflows/cd.yml
=> merge workflows introduced in pr #548

.devcontainer/docker-compose.yml
Update docker compose to use latest tag
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/624
=> Use latest tag

.github/workflows/cd.yml
https://github.com/Energinet-DataHub/geh-timeseries/pull/566
=> Fix notify
