Energinet-DataHub/geh-timeseries

source/GreenEnergyHub.TimeSeries/GreenEnergyHub.TimeSeries.sln, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/GreenEnergyHub.TimeSeries.Domain.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/CorrelationContext.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/ICorrelationContext.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/GreenEnergyHub.TimeSeries.MessageReceiver.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/HealthStatus.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/Properties/serviceDependencies.json, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/Properties/serviceDependencies.local.json, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/Startup.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/TimeSeriesHttpTrigger.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/host.json, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/local.settings.sample.json
The purpose of this PR is to add the MessageReceiver Azure Function to the domain solution.
For now, it will simply reply with HTTP OK on Post requests.
Adding the function to our pipeline will be added in a separate PR.
Besides returning HTTP OK, some simple setup of correlation IDs for later use is also added, as well as preparing the use of NodaTime and adding our HealthStatus endpoint.
* #37
=> Add message receiver HTTP trigger

.github/workflows/message-receiver-cd.yml, .github/workflows/message-receiver-ci.yml
Right now we install core tools without using it, in preparation of moving to .NET 5.0
It turns out that it is not needed to install separately as the .NET Core 3.1 runtime which is needed in the pipelines anyway will actually install it.
As a result, the separate unused steps will be removed.
=> Remove core tools from message receiver pipeline

.github/workflows/pr-env-setup.yml
At the moment we have an open support ticket at CCOE regarding the issue of not being able to support the amounts of service plans needed in the rg-DataHub-Testing-U.
This PR will temporarily disables that workflow until the matter is resolved.
=> Temporary disable of the PR Envoriment Setup

build/infrastructure/azfun-timeseries-message-receiver.tf, build/infrastructure/locals.tf
The purpose of this PR is to add the needed configuration to the MessageReceiver Azure Function to be able to place TimeSeriesCommands on the EventHub.
The actual code updating the MessageReceiver will come in a later PR, this just prepares the needed variables in Terraform deployment.
* #72
=> Update MessageReceiver Terraform with configuration needed to place TimeSeriesCommand on EventHub

source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/TimeSeriesHttpTrigger.cs
The purpose of this PR is to allow us to call the triggers again using anon.
A previous PR had changed this by mistake.
* #77
=> Change authorization level back to anon on message receiver

.github/workflows/streaming-job.yml
Description
Missing RESOURCE_GROUP_NAME is set up in streaming job pipeline.
This PR is an addition to #74
=> Set RESOURCE_GROUP_NAME env pipeline variable

.github/workflows/streaming-job.yml
The purpose of this PR is to fix the broken streaming job pipeline.
* Add short environment name to environment in stream job
=> Fix streaming job pipeline

source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/GreenEnergyHub.TimeSeries.Domain.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/BusinessReasonCode.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/Document.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/DocumentType.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/IndustryClassification.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/MarketParticipant.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/MarketDocument/MarketParticipantRole.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/Notification/TimeSeriesCommand.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/Commands/TimeSeriesCommandConverter.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/Commands/TimeSeriesCommandDeserializer.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MarketDocument/BusinessReasonCodeMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MarketDocument/CimDocumentConverterConstants.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MarketDocument/DocumentConverter.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MarketDocument/DocumentTypeMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/MarketDocument/MarketParticipantRoleMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/GreenEnergyHub.TimeSeries.Tests.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/Infrastructure/Messaging/Serialization/Commands/TimeSeriesCommandConverterTests.cs
The purpose of this PR is to rename our Document based namespaces to use MarketDocument instead of Common in the naming.
This PR contains:
* Domain Common namespace renamed to MarketDocument
* Infrastructure Common namespace named to MarketDocument
* Some housekeeping by removing some unused namespaces in affected files
* Removed empty Common folder from test project
=> Rename Document namespace from Common to MarketDocument

.github/workflows/streaming-job.yml
The purpose of this PR is to fix the storage account name used by the streaming job which was missing the project portion
* #38
=> Fix storage account name to streaming job

source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/HealthStatus.cs
The purpose of this PR is to update the HealthStatus trigger to use isolated syntax.
It was previously failing when called.
=> Update HealthStatus to use isolated function parameters

source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.MessageReceiver/HealthStatus.cs
The purpose of this PR is to use HttpRequestData instead of HttpRequest to be compatible with isolated functions in .NET 5.0
=> Use HttpRequestData in HealthStatus

.github/workflows/sonarcloud-dotnet.yml, .github/workflows/sonarcloud-python.yml
This PR will update when Sonarcloud workflow will trigger. Previously the Dotnet Sonarcloud workflow would trigger on updates made to the streaming code.
=> Sonarcloud path update

source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/Notification/Point.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Domain/Notification/Quality.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/Commands/QualityMapper.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Infrastructure/Messaging/Serialization/Commands/TimeSeriesCommandConverter.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/GreenEnergyHub.TimeSeries.Tests.csproj, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/Infrastructure/Messaging/Serialization/Commands/QualityMapperTests.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/Infrastructure/Messaging/Serialization/Commands/TimeSeriesCommandConverterTests.cs, source/GreenEnergyHub.TimeSeries/source/GreenEnergyHub.TimeSeries.Tests/TestFiles/Valid_Hourly_CIM_TimeSeries_WithQuantityMissingFirstPosition.xml
This PR does the following: 
- Make use of the correct quality code for quantity missing **A02**, replacing the fictive D99.
- Renaming QuantityQuality to Quality, adhering to the Timeseries domain language. 
- Adds another unit test to `TimeseriesCommandConverterTests.cs` that takes a valid CIM xml timeseries with quantity missing in the first position.
* #0000
=> Replacing D99 value for QuantityMissing with correct value A02 and renaming QuantityQuality to Quality

.github/workflows/sonarcloud-dotnet.yml
The purpose of this PR is to add the token needed by SonarCloud which is currently missing and making our pipelines fail at random.
=> Fix missing token for SonarCloud pipeline

source/messaging/source/GreenEnergyHub.Messaging.Protobuf.Tests/GreenEnergyHub.Messaging.Protobuf.Tests.csproj, source/messaging/source/GreenEnergyHub.Messaging.Tests/GreenEnergyHub.Messaging.Tests.csproj
In our earlier upgrade to .NET 5 in the Time Series domain, we missed upgrading Microsoft.Extensions.Logging.Abstractions, hence leaving the GreenEnergyHub.Messaging solution unbuildable, which this pull request makes up for.
=> Upgrade Extensions.Logging.Abstractions to .NET 5

docs/contracts.md
The contract for [TimeSeriesAccepted](https://github.com/Energinet-DataHub/geh-timeseries/blob/main/docs/contracts.md#timeseriesaccepted) incorrectly stated:
_"A unique time series identifier"_
This has been changed to
_"A time series identifier provided by the Market Participant. Uniqueness cannot be guaranteed"_
* #0000
=> Fix: Change description for TimeSeriesId in contracts.md to "not unique"

.github/workflows/streaming-job.yml
Python classes must be generated from protobuf contracts before wheel is built and distributed
=> Generate Python classes from Protobuf contracts

.github/actions/databricks-unit-test/Dockerfile, .github/actions/databricks-unit-test/entrypoint.sh, .github/workflows/streaming-job.yml
With this pull request, we remove infrastructure and deployment parts that are not necessary for the protobuf dependency.
=> Remove presumably unnecessary protobuf conda install

source/GreenEnergyHub.TimeSeries.Integration/global.json, source/GreenEnergyHub.TimeSeries/global.json
With the present pull request we introduce the global.json to pin the .Net Core SDK version used.
One global.json is enough to enforce dotnet to a pinned SDK version, but not all IDEs will conform to this version. Therefore a global.json is added for each .Net solution.
* #305
=> Add global.json for both Time Series solutions

.github/workflows/ci.yml, source/TimeSeries/Infrastructure/Functions/HttpResponseBuilder.cs, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs
`CorrelationId` is now set as a header upon the incoming and outgoing message from APIM. So there is no longer a need for the specific domain to be setting the header.
* #0000
=> Removed CorrealtionId header

.github/actions/databricks-unit-test/Dockerfile, .github/actions/databricks-unit-test/action.yml, .github/actions/databricks-unit-test/entrypoint.sh, .github/actions/databricks-unit-test/spark-defaults.conf, .github/workflows/cd.yml, .github/workflows/ci.yml, build/primary/main/func-time-series-bundle-ingestor.tf, build/primary/main/kv-shared-resources.tf, source/.editorconfig, source/Directory.Build.props, source/TimeSeries/Application/Application.csproj, source/TimeSeries/Infrastructure/Infrastructure.csproj, source/TimeSeries/IntegrationTests/Fixtures/TimeSeriesFunctionAppFixture.cs, source/TimeSeries/IntegrationTests/IntegrationTests.csproj, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs, source/TimeSeries/TestCore/Assets/TestDocuments.cs, source/TimeSeries/TestCore/TestCore.csproj, source/TimeSeries/TimeSeriesBundleIngestor/TimeSeriesBundleIngestor.csproj, source/TimeSeries/UnitTests/UnitTests.csproj
Upgrade Time Series to .NET 6 and function v4.
Important:
* Focus is on upgrading to .NET 6 and functions v4. Only NuGet packages directly impacted by this (e.g. Analyzers) has been updated.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/257
=> Upgrade to .NET 6 and Functions v4

source/TimeSeries/Application/TimeSeriesForwarder.cs, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs
Adds sender_MarketParticipant.mRID to the file name of the json file saved in timeseries raw, to make sure that the file name is unique
* #0000
=> update timeseries raw file name with market participant id

source/databricks/package/timeseries_persister.py
Adding storedTime of when data was stored in the parquet table. This is used for partitioning. And for filtering on time when we want to know how data looked at a specific time in history
* #32
=> add storedtime

source/TimeSeries/Application/TimeSeriesForwarder.cs, source/TimeSeries/IntegrationTests/TimeSeriesBundleIngestionEndpointTests.cs
The chosen json file names caused this problem in Spark:
```
22/08/08 09:25:46 ERROR MicroBatchExecution: Query [id = bf35b7dc-5955-4dfd-b5fc-0ff0a9dde5e5, runId = 5c966487-5696-4643-93c6-e37c836e1247] terminated with error
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: actor=8200000007739-document=DocId2022-08-08T09:22:20.459Z.json
at org.apache.hadoop.fs.Path.initialize(Path.java:263)
```
* https://github.com/Energinet-DataHub/opengeh-wholesale/issues/32
=> Fix bad json file names

.github/workflows/cd.yml
As a part of our new rollout strategy, we want to be able to always have an up to date `dotnet_latest` version besides the running version.
This is to support the possibility to find the latest release by the tag name `dotnet_latest`
This is an addition to the CD job, it will only create and maintain a new `dotnet_latest` release.
BE AWARE that we will do another iteration splitting databricks and infrastructure away from the dotnet package, so this is only to introduce a non breaking rollout
=> added create-latest-release to cd

.github/workflows/cd.yml, .github/workflows/ci.yml
Change federated credentials to use "environment" as "subject" when authenticating to Azure in workflows.
https://app.zenhub.com/workspaces/mighty-ducks---the-outlaws-6193fe815d79fc0011e741b1/issues/energinet-datahub/the-outlaws/607
=> Use environment for OIDC

.devcontainer/devcontainer.json
Changes the python language server from Jedi to Pylance.
Pylance is a more advanced language server than Jedi and provides a lot more help when coding, this includes the ability to see if a import is used or not
* #0000
=> Refac: Replace Jedi with Pylance
